### ISSUE TITLE
Hey, do you guys offer support for fabric-sdk-java-gm by any chance?

### ISSUE THREAD

**Issue by XJZhgy** [hxx258456/fabric-admin-sdk-go#1]
Hi hxx,
搞国密的就不说英文了，
请问您或者您的团队是否有java sdk中的国密改造支持，或者计划？我在弄fabric-sdk-java的国密改造，其中的tls改造实在是头大
只能来问问大佬了

**Comment by hxx258456** [comment]
我没有研究过java，你可以去看看twgc他们有没有这方面的研究https://github.com/Hyperledger-TWGC

**Comment by hxx258456** [comment]
我当时改造的时候是只做了go相关的，java，js，ts这些当时直接舍弃了

**Comment by XJZhgy** [comment]
好的好的，感谢大佬的回复以及建议
